### PR TITLE
add space_get function to ovc client directly

### PR DESCRIPTION
**Pull request by andrewayoub**
#### What this PR resolves:
add space_get function to OVC client In order to also support users that only have access to a specific VDC to interact with it using th OVC client

**Version**: 

**Fixes**: #100

### CODE REVIEW

**Comment by rkhamis** [comment]
LGTM.

@yveskerwyn this what you had in mind?

**Comment by yveskerwyn** [comment]
Yes absolutely, many thanks!!

**Comment by rkhamis** [comment]
@yveskerwyn the ovc client cannot go around access rights of OVC itself

**Comment by yveskerwyn** [comment]
@rkhamis in reply to your feedback that `the ovc client cannot go around access rights of OVC itself`:

When user only has admin rights on a specific cloud space, and no rights at all on the account, he can still use the CloudAPI to create a virtual machine - just tested through the Machine API exposed in the End User portal.

It is this use case that we need to support in the OVC client too

**Pull request merged**
